Repository cozy/cozy-client, pull requests merged in 2018-08, with the labels that each got.

#77 Disable regenerator transform in babel preset
  .babelrc
  package.json
  yarn.lock
Labels: in progress

#74 Fix AppCollection
  packages/cozy-stack-client/src/AppCollection.js
  packages/cozy-stack-client/src/CozyStackClient.js
  packages/cozy-stack-client/src/__tests__/AppCollection.spec.js
Labels: enhancement

#78 test: receiving update result should update all containing queries
  packages/cozy-client/src/CozyClient.js
  packages/cozy-client/src/ObservableQuery.js
  packages/cozy-client/src/Query.jsx
  packages/cozy-client/src/__tests__/associations.spec.js
  packages/cozy-client/src/__tests__/connect.spec.jsx
  packages/cozy-client/src/__tests__/store.spec.js
  packages/cozy-client/src/connect.jsx
  packages/cozy-client/src/store/index.js
  packages/cozy-client/src/store/queries.js
Labels: in progress

#79 perf: do not bind functions inside render
  packages/cozy-client/src/Query.jsx
Labels: in progress

#84 docs: Fix link chain usage 🐛
  README.md
Labels: documentation

#83 chore: autopublish
  .travis.yml
  docs/dev.md
  lerna.json
  package.json
  packages/cozy-client/package.json
  yarn.lock
Labels: in progress

#80 feat: add hoc queryConnect and withClient
  package.json
  packages/cozy-client/src/Query.jsx
  packages/cozy-client/src/hoc.js
  packages/cozy-client/src/hoc.spec.js
  packages/cozy-client/src/index.js
Labels: in progress

#81 fix: client.get query will return only 1 result
  packages/cozy-client/src/ObservableQuery.js
  packages/cozy-client/src/Query.jsx
  packages/cozy-client/src/__tests__/ObservableQuery.spec.js
  packages/cozy-client/src/__tests__/store.spec.js
  packages/cozy-client/src/store/documents.js
  packages/cozy-client/src/store/queries.js
Labels: in progress

#85 chore: transpilation instead of bundling
  bin/build
  package.json
  packages/cozy-client/package.json
  packages/cozy-pouch-link/package.json
  packages/cozy-stack-client/package.json
  yarn.lock
Labels: in progress
